x-shared-env: &shared-env
  API_PORT: ${API_PORT:-6868}
  API_HOST: ${API_HOST:-0.0.0.0}

  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-chatbot}
  POSTGRES_EXPOSE_PORT: ${POSTGRES_EXPOSE_PORT:-5432}

  GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}


version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: chatbot-api:latest
    entrypoint: uvicorn src.api.main:app --host ${API_HOST:-0.0.0.0} --port ${API_PORT:-6868}

    ports:
      - '${API_PORT:-6868}:${API_PORT:-6868}'

    environment:
      <<: *shared-env
      PG_CONNECTION: postgresql+psycopg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_EXPOSE_PORT:-5432}/${POSTGRES_DB:-chatbot}

    restart: unless-stopped

    depends_on:
      - postgres


  postgres:
    image: pgvector/pgvector:pg16

    environment:
      <<: *shared-env

    ports:
      - '${POSTGRES_PORT:-5432}:5432'

    volumes:
      - ./data/pgvector_data:/var/lib/postgresql/data

    restart: unless-stopped
