FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        curl \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /
ENV PYTHONPATH=.

RUN pip install --no-cache-dir chainlit

COPY demo demo